version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing AWS CLI"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - echo "Installing Terraform"
      - curl -LO https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_linux_amd64.zip
      - unzip terraform_1.9.2_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Fetching and setting SSM parameters"
      - ./fetch_and_set_ssm_parameters.sh
  build:
    commands:
      - cd terraform
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
artifacts:
  files:
    - "**/*"
