version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing AWS CLI"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - echo "Installing Terraform"
      - echo "Installing tfenv for Terraform management"
      - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - export PATH=$PATH:$HOME/.tfenv/bin
      - tfenv install 1.9.2
      - tfenv use 1.9.2
      - terraform --version
  pre_build:
    commands:
      - echo "Disabling pyenv version management temporarily"
      - export PYENV_VERSION=system
      - echo "Fetching and setting SSM parameters"
      - aws ssm get-parameters-by-path --path "/terraform" --recursive --query "Parameters[*].{Name:Name,Value:Value}" --output json | jq -r '.[] | "\(.Name | gsub("^/terraform/"; "")) = \"\(.Value)\""' > terraform/ml_resources/terraform.tfvars
      - echo "terraform.tfvars contents:"
      - cat terraform/ml_resources/terraform.tfvars
  build:
    commands:
      - cd terraform/ml_resources
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
artifacts:
  files:
    - "**/*"
